groups:
- name: Request-rates
  rules:
  - alert: ProdRequestsElevated
    expr: sum(rate(requests{space="teaching-vacancies-production", app="teaching-vacancies-production"}[5m]))*60 > 250
    labels:
      environment: production
      severity: medium
    annotations:
      summary: Per-minute request rate high
  - alert: ProdRequestsFailuresElevated
    expr: sum(rate(requests{space="teaching-vacancies-production", app="teaching-vacancies-production", status_range=~"0xx|4xx|5xx"}[5m]))*60 > 25
    labels:
      environment: production
      severity: high
    annotations:
      summary: Per-minute failed requests rate high
- name: CPU-usage
  rules:
  - alert: ProdCPUHigh
    expr: sum(rate(cpu{space="teaching-vacancies-production", app="teaching-vacancies-worker-production"}[5m])) > 5
    labels:
      environment: production
      severity: high
    annotations:
      summary: Worker CPU usage high
  - alert: ProdCPUHigh
    expr: sum(rate(cpu{space="teaching-vacancies-production", app="teaching-vacancies-production"}[5m])) > 5
    labels:
      environment: production
      severity: high
    annotations:
      summary: App CPU usage high
- name: DB-connections
  rules:
  - alert: ProdDBConnectionsNone
    expr: connections{service="teaching-vacancies-postgres-production"} == 0
    labels:
      environment: production
      severity: high
    annotations:
      summary: No DB Connections
  - alert: ProdDBConnectionsElevated
    expr: connections{service="teaching-vacancies-postgres-production"} > 22
    labels:
      environment: production
      severity: medium
    annotations:
      summary: DB connections above 22
  - alert: ProdDBConnectionsLower
    expr: connections{service="teaching-vacancies-postgres-production"} < 8
    labels:
      environment: production
      severity: low
    annotations:
      summary: DB connections below 8

- name: Disk-utilisation
  rules:
  - alert: ProdAppDiskBytesHigh
    expr: sum(rate(disk_bytes{space="teaching-vacancies-production", app="teaching-vacancies-production"}[5m]))/1000000 > 10
    labels:
      environment: production
      severity: high
    annotations:
      summary: App Disk Bytes High
  - alert: ProdWorkerDiskBytesHigh
    expr: sum(rate(disk_bytes{space="teaching-vacancies-production", app="teaching-vacancies-worker-production"}[5m]))/1000000 > 3
    labels:
      environment: production
      severity: high
    annotations:
      summary: Worker Disk Bytes High
- name: Memory-utilisation
  rules:
  - alert: ProdWorkerMemoryUtilizationHigh
    expr: max(memory_utilization{space="teaching-vacancies-production", app="teaching-vacancies-worker-production"}) > 70
    labels:
      environment: production
      severity: high
    annotations:
      summary: Worker Memory Utilization High
  - alert: ProdAppMemoryUtilizationHigh
    expr: max(memory_utilization{space="teaching-vacancies-production", app="teaching-vacancies-production"}) > 70
    labels:
      environment: production
      severity: high
    annotations:
      summary: App Memory Utilization High

- name: Crashed-apps
  rules:
  - alert: ProdAppsCrashed
    expr: sum by (space) (crash{space=~"teaching-vacancies-production"}) > 0
    labels:
      environment: production
      severity: high
    annotations:
      summary: Crashed Production Apps non-zero
  - alert: StagingAppsCrashed
    expr: sum by (space) (crash{space=~"teaching-vacancies-staging"}) > 0
    labels:
      environment: staging
      severity: high
    annotations:
      summary: Crashed Staging Apps non-zero
  - alert: DevAppsCrashed
    expr: sum_over_time(crash{space=~"teaching-vacancies-dev"}[5m]) > 0
    labels:
      environment: dev
      severity: low
    annotations:
      summary: Crashed Dev Apps non-zero

- name: Wrong-number-of-apps
  rules:
  - alert: ProdAppsTooFew
    expr: count(memory_utilization{space=~"teaching-vacancies-production"}) < 6
    labels:
      environment: production
      severity: high
    annotations:
      summary: Fewer than 6 apps in Production
  - alert: ProdAppsTooMany
    expr: count(memory_utilization{space=~"teaching-vacancies-production"}) > 6
    labels:
      environment: production
      severity: medium
    annotations:
      summary: More than 6 apps in Production
  - alert: StagingAppsTooMany
    expr: count(memory_utilization{space=~"teaching-vacancies-staging"}) > 4
    labels:
      environment: staging
      severity: low
    annotations:
      summary: More than 4 apps in Staging
  - alert: StagingAppsTooFew
    expr: count(memory_utilization{space=~"teaching-vacancies-staging"}) < 4
    labels:
      environment: staging
      severity: high
    annotations:
      summary: Fewer than 6 apps in Staging
  - alert: DevAppsTooMany
    expr: count(memory_utilization{space=~"teaching-vacancies-dev"}) > 4
    labels:
      environment: dev
      severity: low
    annotations:
      summary: More than 4 apps in Dev
  - alert: DevAppsTooFew
    expr: count(memory_utilization{space=~"teaching-vacancies-dev"}) < 4
    labels:
      environment: dev
      severity: low
    annotations:
      summary: Fewer than 4 apps in Dev
